# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "nvidia" ];
  boot.kernelModules = [ "kvm-amd" "nvidia_x11"];
  boot.extraModulePackages = [ ];
  boot.blacklistedKernelModules = [ "nouveau" ];
  boot.kernelParams = [ "pci=noats" ];
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1afffb8f-6be8-4e1a-95f3-b98b9b598761";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FC36-C126";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/fb3e4d9e-cc7c-4781-a433-56e130256907";
      fsType = "ext4";
    };

  swapDevices = [ ];

  hardware.system76.enableAll = true;

}
